### ISSUE TITLE
Specify `os` key in `package.json`

### ISSUE THREAD

**Issue by kimlimjustin** [kenan2002/electron-clipboard-ex#2]
I tried this package and it's nice. However, I see that it doesn't support Linux as mentioned in the readme file at the moment, does it better to specify the `os` key in `package.json` to avoid errors when installing other dependencies on Linux cuz npm/yarn will auto exclude it? Thanks! (Btw, please support Linux haha)

**Comment by kenan2002** [comment]
@kimlimjustin Thank you for your advice. I will specify the `os` filed in `package.json` in the next release.
Linux is currently not supported mainly because I'm not familiar with Linux programming. I will look into it if I have time. You can add Linux support now if you are interested :)

**Comment by kimlimjustin** [comment]
> @kimlimjustin Thank you for your advice. I will specify the `os` filed in `package.json` in the next release.
> Linux is currently not supported mainly because I'm not familiar with Linux programming. I will look into it if I have time. You can add Linux support now if you are interested :)

Thanks! I've tried but nothing works yet, if I got the answer, I'll surely open a PR :)

**Comment by kenan2002** [comment]
closed by https://github.com/kenan2002/electron-clipboard-ex/commit/a0b08b40005ee1a13a32fd277db7141d0e6e2c49

**Comment by FatShen3** [comment]
> closed by [a0b08b4](https://github.com/kenan2002/electron-clipboard-ex/commit/a0b08b40005ee1a13a32fd277db7141d0e6e2c49)

Waiting for the new relase to fix this issue

**Comment by kenan2002** [comment]
> > closed by [a0b08b4](https://github.com/kenan2002/electron-clipboard-ex/commit/a0b08b40005ee1a13a32fd277db7141d0e6e2c49)
> 
> Waiting for the new relase to fix this issue

Just published 1.3.3.

**Comment by kimlimjustin** [comment]
Thanks!
