### ISSUE TITLE
Uncaught error

### ISSUE THREAD

**Issue by billyang1222** [kenan2002/electron-clipboard-ex#5]
After npm i electron-clipboard-ex  ,  npm run start,  The following error occurred， How can I solve this problem
Uncaught ReferenceError: process is not defined
    at Object.4043 (<anonymous>:2:13168)
    at r (<anonymous>:2:306599)
    at Object.8048 (<anonymous>:2:9496)
    at r (<anonymous>:2:306599)
    at Object.8641 (<anonymous>:2:1379)
    at r (<anonymous>:2:306599)
    at <anonymous>:2:315627
    at <anonymous>:2:324225
    at <anonymous>:2:324229
    at HTMLIFrameElement.e.onload

**Comment by kenan2002** [comment]
@FireMapleLeaves Could you kindly help to provide your OS version, node version, c++ compiler version and your runtime env if possible?

**Comment by FireMapleLeaves** [comment]
node 12.22.11  win10 64 ,i will check these later，could you please tell me which version does it support ?

**Comment by billyang1222** [comment]
> @FireMapleLeaves Could you kindly help to provide your OS version, node version, c++ compiler version and your runtime env if possible?

node 12.22.11  win10 64 ,i will check these later，could you please tell me which version does it support ?

**Comment by kenan2002** [comment]
> > @FireMapleLeaves Could you kindly help to provide your OS version, node version, c++ compiler version and your runtime env if possible?
> 
> node 12.22.11 win10 64 ,i will check these later，could you please tell me which version does it support ?

I run the test on node 10 12 and 14 on win10 and macOS. Your OS & node version should be supported. I can't reproduce this on my machine. If you have found more info, kindly help to post it here to allow me to reproduce it here.

**Comment by billyang1222** [comment]
> > > @FireMapleLeaves Could you kindly help to provide your OS version, node version, c++ compiler version and your runtime env if possible?
> > 
> > 
> > node 12.22.11 win10 64 ,i will check these later，could you please tell me which version does it support ?
> 
> I run the test on node 10 12 and 14 on win10 and macOS. Your OS & node version should be supported. I can't reproduce this on my machine. If you have found more info, kindly help to post it here to allow me to reproduce it here.

Thanks. I'm a new hand at node and electron，this library is developed by C++ ，What other environments (except node and electron) do I need to install

**Comment by kenan2002** [comment]
> > > > @FireMapleLeaves Could you kindly help to provide your OS version, node version, c++ compiler version and your runtime env if possible?
> > > 
> > > 
> > > node 12.22.11 win10 64 ,i will check these later，could you please tell me which version does it support ?
> > 
> > 
> > I run the test on node 10 12 and 14 on win10 and macOS. Your OS & node version should be supported. I can't reproduce this on my machine. If you have found more info, kindly help to post it here to allow me to reproduce it here.
> 
> Thanks. I'm a new hand at node and electron，this library is developed by C++ ，What other environments (except node and electron) do I need to install

It should not require C++ env because I made it prebuilt, but I'm not sure since I haven't tested it on a machine without C++ env.

**Comment by FireMapleLeaves** [comment]
its a problem about react , see this, https://stackoverflow.com/questions/70368760/react-uncaught-referenceerror-process-is-not-defined  , but i can not understand why there is no problem without this library

**Comment by billyang1222** [comment]
> > > > > @FireMapleLeaves Could you kindly help to provide your OS version, node version, c++ compiler version and your runtime env if possible?
> > > > 
> > > > 
> > > > node 12.22.11 win10 64 ,i will check these later，could you please tell me which version does it support ?
> > > 
> > > 
> > > I run the test on node 10 12 and 14 on win10 and macOS. Your OS & node version should be supported. I can't reproduce this on my machine. If you have found more info, kindly help to post it here to allow me to reproduce it here.
> > 
> > 
> > Thanks. I'm a new hand at node and electron，this library is developed by C++ ，What other environments (except node and electron) do I need to install
> 
> It should not require C++ env because I made it prebuilt, but I'm not sure since I haven't tested it on a machine without C++ env.

its a problem about react , see this, https://stackoverflow.com/questions/70368760/react-uncaught-referenceerror-process-is-not-defined , but i can not understand why there is no problem without this library
