### ISSUE TITLE
I have this working on W10 but for some reason it does not work on W11

### ISSUE THREAD

**Issue by codingedgar** [kenan2002/electron-clipboard-ex#9]
Is somebody else having this issue?

**Comment by warpdesign** [comment]
Can anyone confirm the problem? I am planning to use this module but this could be a stopper :/

**Comment by kenan2002** [comment]
@codingedgar @warpdesign I don't reproduce this. What errors do you get?

**Comment by warpdesign** [comment]
@kenan2002 I didn't try it myself as I only have machines running Windows 10. But the app I'm working on is targeting Win10+Win11 (ARM64/x64) so if it doesn't work on Windows 11 I won't be able to use it.

**Comment by codingedgar** [comment]
I have some clients that are presenting an issue where the copy-paste is not working, however I tried this in a new W11 and could not reproduce it myself.

I'll try to see if I can find more information in why is it failing.

**Comment by warpdesign** [comment]
Anything new regarding this issue? @codingedgar

**Comment by codingedgar** [comment]
I could not find why this is happening in some windows machines, if I encounter anything new I'll reopen
